### PR TITLE
feat(schedule): crud

### PR DESCRIPTION
**Pull request by victorkamoto**
I'm using this library and wanted to use schedules, however, only the create() method was implemented. I've added the rest according to the API reference.

### CODE REVIEW

**Comment by jamescmartinez** [comment]
Thank you, @victorkamoto, this looks great. The only thing missing before this is merged are tests. 

Here are the equivalent tests for tasks; they should be easy enough to copy to schedules: https://github.com/mergentlabs/mergent-js/blob/main/test/resources/Tasks.test.ts

**Comment by victorkamoto** [comment]
I've added the tests @jamescmartinez.

**Comment by jamescmartinez** [comment]
Thanks @victorkamoto - merged. I'll cut a new release today.

**Comment by jamescmartinez** [comment]
@victorkamoto 1.7.0 has been released which contains your Schedule resources, along with some additional typing & e2e tests I added after merging your PR.

**Comment by victorkamoto** [comment]
> some additional typing & e2e tests I added after merging your PR

I missed that, thank you @jamescmartinez

**Pull request merged**
